openapi: 3.1.0
info:
  title: ISOTEC Sanierungs-API
  version: 1.3.0
  description: >
    API zur Unterstützung der ISOTEC-Sanierung: Analyse, Preisrechner, Ansprechpartner per Name, GPT-Auswertung.
servers:
  - url: https://isotec-api.onrender.com
    description: ISOTEC Render-Backend

paths:
  /analyse-schaden:
    post:
      operationId: analyseSchaden
      summary: Analysiert das Schadensbild
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                schadensbild:
                  type: string
                  example: Salzausblühungen an Wandfuß
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  schadenstyp:
                    type: string
                  sanierungsloesung:
                    type: string
                  kundenvorteil:
                    type: string

  /kalkulation:
    post:
      operationId: kalkulationBerechnen
      summary: Berechnet Sanierungskosten
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
              oneOf:
                - required: [gewerk, flaeche_qm]
                  properties:
                    gewerk:
                      type: string
                      example: Innenabdichtung
                    flaeche_qm:
                      type: number
                      example: 25
                - required: [gewerke, flaeche_qm]
                  properties:
                    gewerke:
                      type: array
                      items:
                        type: string
                      example: ["Horizontalsperre", "Innenabdichtung"]
                    flaeche_qm:
                      type: number
                      example: 12
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      einheitspreis:
                        type: number
                      gesamtpreis:
                        type: number
                  - type: object
                    properties:
                      details:
                        type: array
                        items:
                          type: object
                          properties:
                            gewerk:
                              type: string
                            preisProQm:
                              type: number
                            teilpreis:
                              type: number
                      gesamtpreis:
                        type: number

  /ansprechpartner-name:
    get:
      operationId: ansprechpartnerFindenName
      summary: Findet Ansprechpartner anhand des Namens
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: Teilname eines ISOTEC-Ansprechpartners
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  position:
                    type: string
                  telefon:
                    type: string
                  email:
                    type: string

  /generate-auswertung:
    post:
      operationId: auswertungGenerieren
      summary: Generiert eine Sanierungsauswertung mit GPT und Word-Bericht
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                berater:
                  type: string
                kunde:
                  type: string
                adresse:
                  type: string
                objektart:
                  type: string
                schadensbild:
                  type: string
                massnahme:
                  type: object
                  properties:
                    beschreibung:
                      type: string
                    flaeche_qm:
                      type: number
                horizontalsperre:
                  type: object
                  properties:
                    typ:
                      type: string
                    laenge_m:
                      type: number
                alternativen:
                  type: array
                  items:
                    type: object
                    properties:
                      bezeichnung:
                        type: string
                      flaeche_qm:
                        type: number
                      preis_pro_qm:
                        type: number
                      aufpreis_pro_qm:
                        type: number
      responses:
        "200":
          description: Erfolgreich generiert
          content:
            application/json:
              schema:
                type: object
                properties:
                  bericht:
                    type: string
                  kalkulation:
                    type: object
                    properties:
                      standard:
                        type: number
                      variante2:
                        type: number
                      variante3:
                        type: number
                  download_url:
                    type: string
